# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing. 
# Edit from developer: LOL I edited it I'm gonna fucking cry


from PyQt5 import QtCore, QtGui, QtWidgets
import threading as t
import client
import threading


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        # Most of this was generated by the PyQt designer

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 490, 101, 91))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.TXT = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TXT.setGeometry(QtCore.QRect(0, 490, 691, 91))
        self.TXT.setObjectName("TXT")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 801, 491))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 799, 489))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.data = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.data.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(26)
        self.data.setFont(font)
        self.data.setTextFormat(QtCore.Qt.AutoText)
        self.data.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.data.setObjectName("data")
        self.horizontalLayout.addWidget(self.data)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.connected = False
        '''
        So we'll be storing all of our messages on the client side
        The reason I'm doing this is because if we would want to store
        the message on the server, we'd have to create a new class that stores the messages of every 
        seperate room, I cba doing that, this is just easier (lazier).
        '''
        self.messages = []


    def retranslateUi(self, MainWindow, tekst=""):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "CLICK"))
        self.pushButton.clicked.connect(self.on_click)
        self.data.setText(_translate("MainWindow", tekst))

    def on_click(self):
        if self.TXT.toPlainText() == "":
            return

        if self.connected == False:
            if "/connect" not in self.TXT.toPlainText():
                self.EditLabel("Please connect to a room first....\nCommand: /connect (roomnumber)\n")
                return;
            else:
                for i in self.TXT.toPlainText().split():
                    if i.isnumeric():
                        room = int(i)
                        self.room = room
                        break

                self.EditLabel(f"Trying to connect to room {room}...\n")
                self.connectServer(room)
                self.TXT.setPlainText("")

                return



        
        if len(self.TXT.toPlainText()) > 1024:
            self.EditLabel("Your message is too long...")
            return


        connection.GetUiMessage(self.TXT.toPlainText())
        self.TXT.setPlainText("")


    def connectServer(self, NumerRoom):
        global connection
        self.connected = True
        PORT = 6969
        IP = "localhost"

        connection = client.Connection(self)
        connection.connect(IP, PORT, NumerRoom)

        listener = threading.Thread(target=connection.receive)
        listener.start()


    def EditLabel(self, MESSAGE):
        if MESSAGE == "The room you tried to connect to is full\nplease try again\n":
            self.connected=False
        
        total = ""
        self.messages.append(MESSAGE)
        for i in self.messages:
            total += i
        translate = QtCore.QCoreApplication.translate # I have no idea wtf this does, but apparently you need it to change the label so lol
        self.data.setText(translate("MainWindow", total))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())